# Generated by Django 6.0.1 on 2026-02-05 21:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_meeting_actual_end_meeting_allowed_participants_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='forumpayment',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='forumpayment',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='forumpayment',
            name='type',
            field=models.CharField(choices=[('DUES', 'Dues'), ('CONTRIBUTION', 'Contribution'), ('LEVY', 'Levy'), ('DISBURSEMENT', 'Disbursement')], default='DUES', max_length=20),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='forumpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='forumwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterUniqueTogether(
            name='memberpayment',
            unique_together={('payment', 'user')},
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FIXED', 'Fixed'), ('CATEGORY', 'Category/Criterion-based')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount_per_member', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('criteria', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='forums.forum')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('below_18', 'Below 18'), ('age_18_plus', '18 and above'), ('youth', 'Youth'), ('mothers', 'Mothers'), ('fathers', 'Fathers'), ('junior', 'Junior'), ('senior', 'Senior')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='payments.forumpayment')),
            ],
            options={
                'unique_together': {('payment', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PaymentUserWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dest_forum_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='payments.forumwallet')),
                ('dest_user_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='payments.paymentuserwallet')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='forums.forum')),
                ('source_forum_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='payments.forumwallet')),
                ('source_user_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='payments.paymentuserwallet')),
            ],
        ),
        migrations.DeleteModel(
            name='ForumWalletTransaction',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
