# Generated by Django 6.0.1 on 2026-02-06 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_withdrawalrequest_forum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='amount_per_member',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='criteria',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='title',
            field=models.CharField(default='Disbursement', max_length=150),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='type',
            field=models.CharField(choices=[('PAY_ALL', 'Pay to All Members'), ('PAY_SELECTED', 'Pay to Selected Members')], default='PAY_ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpayment',
            name='type',
            field=models.CharField(choices=[('DUES', 'Dues'), ('CONTRIBUTION', 'Contribution'), ('LEVY', 'Levy')], default='DUES', max_length=20),
        ),
        migrations.CreateModel(
            name='DisbursementCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='payments.disbursement')),
                ('members', models.ManyToManyField(blank=True, related_name='disbursement_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('disbursement', 'category_name')},
            },
        ),
    ]
