# Generated by Django 6.0.1 on 2026-02-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_disbursement_amount_per_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='type',
            field=models.CharField(choices=[('PAY_ALL', 'Pay to All Members (with Categories)'), ('PAY_SELECTED', 'Pay to Selected Members'), ('PAY_TO_ALL', 'Pay to All Members (Fixed Amount)')], default='PAY_ALL', max_length=20),
        ),
    ]
