# Generated by Django 6.0.1 on 2026-02-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_disbursement_executed_at_alter_disbursement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumwallet',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
