# Generated by Django 4.2.10 on 2026-08-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentuserwallet_wallet_number_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpayment',
            name='levy_basis',
            field=models.CharField(choices=[('GENDER', 'Gender Based'), ('AGE', 'Age Based')], default='GENDER', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='category',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('below_18', 'Below 18'), ('age_18_plus', '18 and above')], max_length=50),
        ),
    ]
