# Generated by Django 6.0.1 on 2026-08-20 11:29

import uuid

from django.db import migrations, models


def backfill_wallet_numbers(apps, schema_editor):
    ForumWallet = apps.get_model("payments", "ForumWallet")
    PaymentUserWallet = apps.get_model("payments", "PaymentUserWallet")

    for model, prefix in ((ForumWallet, "FW"), (PaymentUserWallet, "UW")):
        used = set(model.objects.exclude(wallet_number__isnull=True).exclude(wallet_number="").values_list("wallet_number", flat=True))
        for wallet in model.objects.filter(wallet_number__isnull=True) | model.objects.filter(wallet_number=""):
            candidate = f"{prefix}{uuid.uuid4().hex[:10].upper()}"
            while candidate in used:
                candidate = f"{prefix}{uuid.uuid4().hex[:10].upper()}"
            wallet.wallet_number = candidate
            wallet.save(update_fields=["wallet_number"])
            used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_disbursement_approval'),
    ]

    operations = [
        migrations.RunPython(backfill_wallet_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='forumwallet',
            name='wallet_number',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentuserwallet',
            name='wallet_number',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
