# Generated by Django 4.2.10 on 2026-07-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_adminrole_independentforumrequest'),
        ('alumni', '0002_schoolmembership_role'),
    ]

    operations = [
    ]
