# Generated by Django 4.2.10 on 2026-07-18 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumni', '0004_school_country_school_lga_school_state_school_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary'), ('PATRON', 'Patron')], default='MEMBER', max_length=20),
        ),
        migrations.CreateModel(
            name='SchoolJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='school_join_certs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='alumni.schoolforum')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_school_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'forum')},
            },
        ),
    ]
