# Generated by Django 4.2.10 on 2026-07-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alter_schoolmembership_role_schooljoinrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schooljoinrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schooljoinrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
