# Generated by Django 6.0.1 on 2026-07-22 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_add_school_and_forum_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary'), ('PATRON', 'Patron'), ('MODERATOR', 'Moderator')], default='MEMBER', max_length=20),
        ),
        migrations.CreateModel(
            name='SchoolForumMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='alumni.schoolforum')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_forum_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
