# Generated by Django 4.2.10 on 2026-07-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_forumrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumrequest',
            name='visibility',
            field=models.CharField(blank=True, default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('COLLEGE', 'College'), ('TECHNICAL', 'Technical School'), ('UNIVERSITY', 'University'), ('POLYTECHNIC', 'Polytechnic'), ('COLLEGE_OF_EDUCATION', 'College of Education'), ('OTHER', 'Other')], default='SECONDARY', max_length=20),
        ),
    ]
