# Generated by Django 6.0.1 on 2026-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_forumrequest_visibility_school_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumrequest',
            name='join_policy',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=20),
        ),
    ]
