# Generated by Django 4.2.10 on 2026-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
