# Generated by Django 6.0.1 on 2026-08-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
