# Generated by Django 6.0.1 on 2026-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_username_profile_username_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
