# Generated by Django 6.0.1 on 2026-01-27 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='forum_logos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SA', 'Sole Admin'), ('CP', 'Chairperson'), ('VC', 'Vice Chairperson'), ('SEC', 'Secretary'), ('FSEC', 'Financial Secretary'), ('PRO1', 'Provost 1'), ('PRO2', 'Provost 2'), ('PRO3', 'Provost 3'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='forums.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'forum')},
            },
        ),
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meetings_attended', models.IntegerField(default=0)),
                ('payments_completed', models.IntegerField(default=0)),
                ('chats_sent', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('activity_score', models.IntegerField(default=0)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='forums.forummembership')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ring_color', models.CharField(choices=[('GRAY', 'Gray'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='GRAY', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ring', to='forums.forummembership')),
            ],
        ),
    ]
