# Generated by Django 6.0.1 on 2026-02-03 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='forum',
            name='constitution',
            field=models.FileField(blank=True, null=True, upload_to='forum_docs/'),
        ),
        migrations.AddField(
            model_name='forum',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='forum',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forum',
            name='is_searchable',
            field=models.BooleanField(default=True, help_text='Allow forum to appear in searches'),
        ),
        migrations.AddField(
            model_name='forum',
            name='motto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='objectives_rules',
            field=models.TextField(blank=True, help_text='Forum objectives and rules'),
        ),
        migrations.AddField(
            model_name='forum',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='forum',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='forum_logos/'),
        ),
        migrations.AddField(
            model_name='forum',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='forum_certs/'),
        ),
        migrations.AddField(
            model_name='forum',
            name='registration_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='slogan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='forum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ForumJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='forums.forum')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'forum')},
            },
        ),
    ]
