# Generated by Django 6.0.1 on 2026-02-04 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_announcement_forummeeting_forumpayment_forumpost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='forum_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='invitation_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='forumjoinrequest',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ForumInvitationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('usage_type', models.CharField(choices=[('SINGLE', 'Single Use'), ('MULTIPLE', 'Multiple Uses'), ('LIMITED', 'Limited Uses')], default='MULTIPLE', max_length=10)),
                ('max_usage_count', models.IntegerField(blank=True, null=True)),
                ('current_usage_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitation_codes', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='forums.forum')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
