# Generated by Django 6.0.1 on 2026-02-05 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_alter_forummeeting_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='actual_end',
            field=models.DateTimeField(blank=True, help_text='Admin-set end time (overrides scheduled_end)', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='allowed_participants',
            field=models.ManyToManyField(blank=True, help_text='If empty, all forum members can join. If populated, only these users can join.', related_name='allowed_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_all_members_allowed',
            field=models.BooleanField(default=True, help_text='If True, all forum members can join. If False, only allowed_participants can join.'),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='is_marked_present',
            field=models.BooleanField(default=False, help_text='Was user present for sufficient duration?'),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='presence_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of meeting time attended (0-100)'),
        ),
    ]
