# Generated by Django 6.0.1 on 2026-02-08 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_forumdocument_forumsettings_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('email_error', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('FORUM', 'Forum Announcement'), ('EMAIL', 'Email Announcement')], default='FORUM', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='save_to_forum_feed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcementread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['forum', '-created_at'], name='forums_anno_forum_i_b44ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_archived'], name='forums_anno_is_arch_f69705_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['announcement'], name='forums_anno_announc_18f83d_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user'], name='forums_anno_user_id_12c06c_idx'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_recipients', to='forums.announcement'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_emails_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcementrecipient',
            index=models.Index(fields=['announcement'], name='forums_anno_announc_3cb9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementrecipient',
            index=models.Index(fields=['user'], name='forums_anno_user_id_8c5083_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together={('announcement', 'user')},
        ),
    ]
