# Generated by Django 6.0.1 on 2026-02-10 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_notification_and_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='pollvote',
            options={'ordering': ['-voted_at']},
        ),
        migrations.RemoveIndex(
            model_name='polloption',
            name='forums_poll_option_poll_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='forums_noti_user_id_5d5e31_idx',
            old_name='forums_notif_user_forum_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='forums_noti_user_id_ba2690_idx',
            old_name='forums_notif_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='forums_noti_forum_i_477612_idx',
            old_name='forums_notif_forum_created_idx',
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='forums_poll_forum_i_45a469_idx',
            old_name='forums_poll_forum_is_ar_idx',
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='forums_poll_start_t_d4a41c_idx',
            old_name='forums_poll_start_end_idx',
        ),
        migrations.RenameIndex(
            model_name='pollgroup',
            new_name='forums_poll_forum_i_f95671_idx',
            old_name='forums_poll_group_forum_is_ar_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='forums_poll_poll_id_448302_idx',
            old_name='forums_poll_vote_poll_voter_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='forums_poll_option__3c3574_idx',
            old_name='forums_poll_vote_option_idx',
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forums.polloption'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes_alt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
