# Generated by Django 6.0.1 on 2026-02-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_alter_polloption_options_alter_pollvote_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_provider', models.CharField(blank=True, choices=[('google', 'Google (OAuth2)'), ('microsoft', 'Microsoft (OAuth2)'), ('smtp', 'SMTP')], max_length=20, null=True)),
                ('oauth_tokens', models.JSONField(blank=True, null=True)),
                ('smtp_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='forums.forum')),
            ],
        ),
    ]
