# Generated by Django 6.0.2 on 2026-02-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_extend_roles_and_activity_history'),
        ('forums', '0014_forumemailsettings'),
    ]

    operations = [
    ]
