# Generated by Django 4.2.10 on 2026-07-26 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0017_memberactivity_schema_sync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementattachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameIndex(
            model_name='forumactivityhistory',
            new_name='forums_foru_forum_i_24cc3f_idx',
            old_name='forums_foru_forum_idx',
        ),
        migrations.RenameIndex(
            model_name='forumactivityhistory',
            new_name='forums_foru_forum_i_e96e8a_idx',
            old_name='forums_foru_forum_tab_idx',
        ),
        migrations.RenameIndex(
            model_name='forumactivityhistory',
            new_name='forums_foru_forum_i_7c17d0_idx',
            old_name='forums_foru_forum_act_idx',
        ),
        migrations.RenameIndex(
            model_name='forumactivityhistory',
            new_name='forums_foru_perform_41398f_idx',
            old_name='forums_foru_perform_idx',
        ),
        migrations.RemoveField(
            model_name='memberactivity',
            name='chats_sent',
        ),
        migrations.RemoveField(
            model_name='memberactivity',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='memberactivity',
            name='payments_completed',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('GENERAL', 'General Announcement'), ('TARGETED', 'Targeted Announcement')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='forums.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumactivityhistory',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the activity'),
        ),
        migrations.AlterField(
            model_name='forumactivityhistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Any additional JSON data'),
        ),
        migrations.AlterField(
            model_name='forumactivityhistory',
            name='object_id',
            field=models.CharField(blank=True, help_text='ID of related object (post, meeting, payment, etc)', max_length=50),
        ),
        migrations.AlterField(
            model_name='forumactivityhistory',
            name='object_type',
            field=models.CharField(blank=True, help_text='Type of related object', max_length=50),
        ),
        migrations.AlterField(
            model_name='forumactivityhistory',
            name='title',
            field=models.CharField(help_text='Activity title/summary', max_length=255),
        ),
    ]
