# Generated by Django 6.0.1 on 2026-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0019_forum_contact_email_forum_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='forum',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='forum',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
