# Generated by Django 6.0.1 on 2026-07-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0020_forum_country_forum_lga_forum_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummembership',
            name='custom_office',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='forummembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('P', 'President'), ('VP', 'Vice President'), ('SEC', 'Secretary'), ('ASEC', 'Assistant Secretary'), ('FSEC', 'Financial Secretary'), ('TR', 'Treasurer'), ('PRO', 'Public Relations Officer'), ('MOD1', 'Founding Moderator 1'), ('MOD2', 'Founding Moderator 2'), ('MOD3', 'Founding Moderator 3'), ('MOD4', 'Founding Moderator 4'), ('MOD5', 'Founding Moderator 5'), ('CUSTOM', 'Custom Executive Office')], default='MEMBER', max_length=10),
        ),
    ]
