# Generated by Django 4.2.10 on 2026-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0023_add_school_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='is_general',
            field=models.BooleanField(default=False, help_text='Automatically generated general alumni forum for a school'),
        ),
    ]
