# Generated by Django 4.2.10 on 2026-08-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0024_alter_forum_is_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
