# Generated by Django 4.2.10 on 2026-08-07 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumni', '0011_forumrequest_join_policy'),
        ('forums', '0025_forum_town'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forum',
            unique_together={('school', 'graduation_year', 'nickname', 'is_general')},
        ),
        migrations.CreateModel(
            name='ForumRoleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('role_type', models.CharField(choices=[('CORE_EXECUTIVE', 'Core Executive'), ('EXECUTIVE', 'Executive')], default='EXECUTIVE', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forum_roles', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_definitions', to='forums.forum')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('forum', 'name')},
            },
        ),
    ]
