# Generated by Django 4.2.10 on 2026-08-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0026_alter_forum_unique_together_forumroledefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsettings',
            name='join_mode',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REQUEST', 'Request'), ('INVITE', 'Invite')], default='REQUEST', max_length=20),
        ),
    ]
