# Generated by Django 6.0.1 on 2026-08-20 03:09

import random
import re

from django.db import migrations, models


def normalize_forum_ids(apps, schema_editor):
    Forum = apps.get_model('forums', 'Forum')
    pattern = re.compile(r'^[A-Z]{2}[0-9]{4}$')
    used = set(Forum.objects.exclude(forum_id__isnull=True).values_list('forum_id', flat=True))

    for forum in Forum.objects.all().iterator():
        if forum.forum_id and pattern.fullmatch(forum.forum_id):
            continue

        while True:
            candidate = ''.join(random.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZ', k=2))
            candidate += ''.join(random.choices('0123456789', k=4))
            if candidate not in used:
                break

        used.discard(forum.forum_id)
        used.add(candidate)
        Forum.objects.filter(pk=forum.pk).update(forum_id=candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0028_inboxmessage_inboxfavorite'),
    ]

    operations = [
        migrations.RunPython(normalize_forum_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='forum',
            name='forum_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
