# Generated by Django 6.0.1 on 2026-08-20 03:15

import forums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0029_alter_forum_forum_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='forum_id',
            field=models.CharField(default=forums.models.generate_forum_id, max_length=6, unique=True),
        ),
    ]
