# Generated by Django 6.0.1 on 2026-08-20 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0030_alter_forum_forum_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='inbox_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forums.inboxmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
