# Generated by Django 6.0.1 on 2026-08-21 14:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0031_inboxmessageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumVerificationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('duration_days', models.PositiveIntegerField(default=365)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['duration_days', 'fee_amount'],
            },
        ),
        migrations.AddField(
            model_name='forumverificationrequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='forums.forumverificationplan'),
        ),
    ]
